"""initial_schema

Revision ID: f15532351672
Revises: 
Create Date: 2026-09-10 21:01:44.793708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f15532351672'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('processed_updates',
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('trial_used', sa.Boolean(), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('business_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('connection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('can_reply', sa.Boolean(), nullable=False),
    sa.Column('rights_json', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_connections_business_connection_id'), ['business_connection_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_connections_user_id'), ['user_id'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_connection_id', 'telegram_chat_id', name='uq_user_conn_chat')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_business_connection_id'), ['business_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_user_id'), ['user_id'], unique=False)

    op.create_table('excluded_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'telegram_chat_id', name='uq_user_excluded_chat')
    )
    with op.batch_alter_table('excluded_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_chats_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excluded_chats_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('telegram_charge_id', sa.String(length=255), nullable=True),
    sa.Column('invoice_payload', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notify_deleted_text', sa.Boolean(), nullable=False),
    sa.Column('notify_edited_messages', sa.Boolean(), nullable=False),
    sa.Column('notify_deleted_photos', sa.Boolean(), nullable=False),
    sa.Column('notify_deleted_videos', sa.Boolean(), nullable=False),
    sa.Column('notify_deleted_voice', sa.Boolean(), nullable=False),
    sa.Column('notify_deleted_documents', sa.Boolean(), nullable=False),
    sa.Column('notify_view_once', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=True),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_username', sa.String(length=255), nullable=True),
    sa.Column('sender_first_name', sa.String(length=255), nullable=True),
    sa.Column('sender_last_name', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('entities_json', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('media_group_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_connection_id', 'telegram_chat_id', 'telegram_message_id', name='uq_business_chat_message')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_business_connection_id'), ['business_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_telegram_message_id'), ['telegram_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=False),
    sa.Column('provider_payment_charge_id', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_first_recurring', sa.Boolean(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_json', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_telegram_payment_charge_id'), ['telegram_payment_charge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('deleted_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id_fk', sa.UUID(), nullable=False),
    sa.Column('business_connection_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id_fk'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_events_message_id_fk'), ['message_id_fk'], unique=False)

    op.create_table('media_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id_fk', sa.UUID(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=500), nullable=False),
    sa.Column('file_unique_id', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=False),
    sa.Column('download_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id_fk'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_objects_file_unique_id'), ['file_unique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_objects_message_id_fk'), ['message_id_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_objects_sha256'), ['sha256'], unique=False)

    op.create_table('message_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id_fk', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('entities_json', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('telegram_edit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id_fk'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id_fk', 'version_number', name='uq_msg_version')
    )
    with op.batch_alter_table('message_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_versions_message_id_fk'), ['message_id_fk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_versions_message_id_fk'))

    op.drop_table('message_versions')
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_objects_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_objects_message_id_fk'))
        batch_op.drop_index(batch_op.f('ix_media_objects_file_unique_id'))

    op.drop_table('media_objects')
    with op.batch_alter_table('deleted_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_events_message_id_fk'))

    op.drop_table('deleted_events')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_telegram_payment_charge_id'))

    op.drop_table('payments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_telegram_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))
        batch_op.drop_index(batch_op.f('ix_messages_business_connection_id'))

    op.drop_table('messages')
    op.drop_table('user_settings')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('excluded_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_excluded_chats_telegram_chat_id'))

    op.drop_table('excluded_chats')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_chats_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_chats_business_connection_id'))

    op.drop_table('chats')
    with op.batch_alter_table('business_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_business_connections_business_connection_id'))

    op.drop_table('business_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))

    op.drop_table('users')
    op.drop_table('processed_updates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
